### PR TITLE
bcrypt: specify length in type signature

### PR DESCRIPTION
**Pull request by euank**
Relates to #273

This PR removes two asserts from the bcrypt implementation by changing slices to fixed-sized-arrays so the type system helps us out.

This also moves the error to compile-time and helps users of the library better understand these expectations.

I'm willing to also make a similar change in various other files which have the same pattern, but I'd like to make sure these sorts of changes make sense before doing so.

This is a breaking change for any users of the bcrypt function.

### CODE REVIEW

**Comment by euank** [comment]
Ehh, properly reading the previous thread I linked, it looks like this isn't wanted for ergonomic reasons. Whoops, sorry for the noise!

**Comment by burdges** [comment]
[arrayref](https://github.com/droundy/arrayref) provides a slice-like interface for fixed length arrays, which fixes those ergonomic issues.  It'll alleviate your main interest in changing rust-crypto though too.  ;)

**Comment by euank** [comment]
@burdges given that, I'll reopen this for discussion at least.

It doesn't alleviate my concern though. Expressing a contract of "the salt is exactly 16 bytes" makes a ton more sense with the type system than with a runtime assert.

**Comment by euank** [comment]
Appears nothing's happening here, closed it is.

**Pull request closed without merging**
