### PR TITLE
Authenticated encryption

### PR DESCRIPTION
**Pull request by calvinmetcalf**
This has the api and GCM mode, I'm almost done with chacha20/poly1305 as well and also figured we could do a generic version that just accepts any cipher and mac combination.

Just to be clear not ready to merge yet.

The api I defined is that the constructor for the aead takes key, iv, additional data (any anything else the cipher needs), then aeads have a trait of encrypt or decrypt that takes input, output, or tag.  For encrypt it writes to the tag and for decrypt you're passing in the tag. It is intentional non-streaming as it verifies the tag before it decrypts.

I had to make some modifications to how ghash worked as I found it changed types when you added ciphered data

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
added chacha20/poly1305 also simplified gcm to only have a AesGcm struct that can be used for both authenticaged encryption and decryption (same with chacha it only has one struct that can be used both ways).

**Comment by DaGenix** [comment]
This is exceptionally exciting work! I haven't had a chance yet to look at it more in depth today, but I'll try to look more at it tomorrow.

**Comment by DaGenix** [comment]
Thanks for your work! I have a couple of questions but I'm quite excited to get this merged.

* Why was it necessary to change how Ghash works?
* Could you add Copyright headers to the new files?
* Do you consider this ready for merging?

@Florob - Do you have any thoughts on the changes to Ghash?

Thanks!

**Comment by calvinmetcalf** [comment]
I can add the copyright notices then it should be good to go, changing ghash was necessary as I couldn't store it in  struct field due to it changing type and the result that got calculated from the hmac wasn't actually correct because it wasn't flushed right.  All I really did was merge the 2 different structs and add some more tests.

**Comment by Florob** [comment]
I'll have to look into it in more detail later, but from a quick glance I'm already quite irritated.
* From what I can tell this AesGcm implementation does not work on more than one block, the CTR-mode part is completely missing
* Ghash now allows `input_a()` to be called after `input_c()`, that must not be possible. I'm quite fond of enforcing it in the type system, but at the very least this needs to panic.
* Could you elaborate a bit on what you think was wrong with the HMAC implementation? I fail to see any difference from looking at the diff, right now.
* I'm not exactly fine with the way the AEAD traits are defined. At the very least I'd want it to return `Result<(), ()>` to get the `#[must_use]` annotation. It might also be sensible to actually return `Result<Vec<u8>, ()>`. Not being sure how to define this is one of the major reasons I did not yet finish my [own implementation](https://github.com/Florob/rust-crypto/blob/gcm/src/rust-crypto/aead.rs). [RFC5116](http://tools.ietf.org/html/rfc5116) has some guidance.

Apart from that, good to see someone else working on this.

**Comment by Florob** [comment]
Upon closer inspection, I retract that comment about CTR-mode, but remain a bit unconvinced that this is in line with the GCM spec… All test cases seem to be smaller than one block.

**Comment by calvinmetcalf** [comment]
I noticed that it's easy to miss the chacha20poly1305 file as it's closed by default, [here is a link](https://github.com/calvinmetcalf/rust-crypto/blob/gcm/src/chacha20poly1305.rs)

- we can guard against a being called after c because c causes flushed to be changed to true after being called, will update.
- c-data was not being updated by calls to raw_result, also raw result was not implimented for the ghash with c, looking how you use 
- the test vector `d9313225f88406e5a55909c5aff5269a86a7a9531534f7da2e4c303d8a318a721c3c0c95956809532fcf0e2449a6b525b16aedf5aa0de657ba637b39` is 3 3/4 blocks long...
- so currently the aead api is just returning a boolean on decryption to say if it succeed, if we wanted to actually return the decryption results then something like  `Result<Vec<u8>, DecodingError>` might make more sense.  Or if we want them to pass their output vector in then maybe `Result<DecodingSuccess, DecodingError>`
- I'm not sure I understand your issues with crt mode, it's defined [here](https://github.com/DaGenix/rust-crypto/pull/221/files#diff-4cfd736b4be09a5976a0d24c998b5ab9R24) and just uses the vanilla crt mode that already exists specifically via it's stream cipher interface (the same way I did for chacha20poly1405)

**Comment by Florob** [comment]
When GHash is used as Mac algorithm there is by definition no c-data, since it is only used to authenticate data This was ensured by implementing it on `Ghash`, something your change also breaks.

My issue with CTR mode is precisely that you use the vanilla one. GCM defines it slightly different, using only the 32 least significant bit as a counter, keeping the higher once in place: "More formally, the value of `incr(F||I)` is `F||(I + 1 mod 2^32)`" [Spec](http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-spec.pdf). I.e. your overflow behaviour is different. I'd guesstimate that the official test-cases would show this.

**Comment by Florob** [comment]
On a slightly related note: While 96-bit nonces are recommended, they are not required as suggested by your current implementation.

**Comment by calvinmetcalf** [comment]
the issue I faced with ghash was that since raw_request did put the authenticated data length in when it flushed it couldn't be used as a straight up mac (say like how poly1305 is used in the chaca20poly1305) it might be easier to just have that be fixed, though now that I've seen your example of how to actually use it I could probably do it that way as well.

the counter issue would only come up if you encrypt more then 2^32 blocks aka 2^37 bytes of data aka 256 gigabytes of data, we can put a check in to make sure the input/output buffers are smaller in size then 256 gigabytes.  None of the test cases in the spec are long enough to trigger this.

as for 96 bit nonces, i figure that can be punted until later as requiring 96 bit nonces is in line with other implementation (openssl)

**Comment by calvinmetcalf** [comment]
reverted the changes to ghash now that I understand the reasoning/expected use.

**Comment by Florob** [comment]
The statement about 2^37 bytes of data is actually very intertwined with 96-bit nonces. If you use anything but 96-bit nonces your IV can turn out to overflow even after a single block/byte, since the counter portion doesn't have to start at 0x00000001. I think I can live with this implementation, but I'd want a comment in the code that emphasises this relation.

On a more general note, it seems to me that both `encrypt()` and `decrypt()` can only be called once in this implementation. As such there doesn't seem to be much benefit from first creating an object, over having a free standing function, or using a unit struct. Do you have any thoughts on what the most sensible way to make the object reusable would be, potentially moving some parameters from `new()` to the `encrypt()`/`decrypt()` methods?

**Comment by calvinmetcalf** [comment]
to make it reuse you'd have to move every thing except key and for gcm key size at which point you might as well call it as a function.  The one benefit I do see to having it separate like this is that some non trivial work is done in the setup to create the keys for the macs so doing that ahead of time might be helpful in certain situations.

Though it's really only the decrypter that should only be called once, the encrypter could have a streaming interface ...

**Comment by DaGenix** [comment]
What standard are you implementing for chacha20poly1305? https://tools.ietf.org/html/draft-agl-tls-chacha20poly1305-01 (which has since expired) seems to say that the input to poly1305 should be aad_len, aad, ciphertext_len, cipher text. This implementation seems to feed them in as aad, aad_len, ciphertext, ciphertext_len.

The interfaces don't seem quite right to me. Since the objects aren't re-usable and since streaming interfaces aren't supported, it might make sense to just do everything in a single function. However, none of the interfaces in rust-crypto are really stabilized at this point and I think all of them need work. So, I see no reason to make any changes here. Maybe once Rust 1.0 comes out, I'd like there to be an effort to revamp all of the interfaces to make sure that they are all right.

Anyway, if you can answer my one last question, I'll merge this tomorrow.

Thanks @calvinmetcalf and @Florob for your work and input.

**Comment by calvinmetcalf** [comment]
this [draft](https://tools.ietf.org/html/draft-agl-tls-chacha20poly1305-04) which is out of date but is the one that boring ssl uses (which is where the test vectors come from), the current version of chacha20 in this library with 8 byte nonces is also from that same draft.

**Comment by calvinmetcalf** [comment]
squashed it, and yes the current api is awkward and pointlessly complex but likely the best bet is to do a big api standarization across all of the apis at the same time.

FYI the most up to date chacha20poly1305 version from what I understand is [this one](https://tools.ietf.org/html/draft-irtf-cfrg-chacha20-poly1305-03) Implementing it would involve updating chacha20 to take 12byte nonces.

**Comment by Florob** [comment]
ProTip: RFCs have different versions linked at the top. Also visiting the URL without the -xx part at the end always gives you the [newest version](https://tools.ietf.org/html/draft-irtf-cfrg-chacha20-poly1305).
In this case that is 08 and not 03. Nonces were indeed changed to 12 bytes a while ago. My understanding is that this was to get the the existing AEAD ciphers in line.

**Comment by calvinmetcalf** [comment]
nice thanks did not know that trick for RFCs (I had been lazy and grabbed the link to the version I used in November to create the JavaScript version), 

The most up to date one (after double checking this is still the case) the order is

- aad
- padding of zeros up to a multiple of 16 (max 15 so zero if already a multiple of 16)
- cipher text
- padding of zeros up to a multiple of 16 (max 15 so zero if already a multiple of 16)
- aad len
- ciphertext len

**Comment by DaGenix** [comment]
I've noticed that the tests don't seem to be working - specifically, it looks to be stuck somewhere in LLVM during compilation. My best guess is that the `vec!()` macro doesn't play well with some of the fairly big test cases. Unless there is some better alternative, I think we may need to reduce the number of test cases until we can find a better workaround. Do you have an oppinion on which test cases are the best to keep? I'm thinking just keep a few of the shorter ones and a few of the longer ones. Thoughts?

After we resolve the test issue, I'll merge this in. I think I'll open two issues to go along with it:

* One to update to the latest RFC (without breaking compatibility with libsodium)
* Another to create some sort of "feature gate" so that users that want to use algorithms based on draft specs have to explicitly opt in. Hopefully that will make it less surprising when we update an implementation to the latest spec.

**Comment by calvinmetcalf** [comment]
I'll comment out some of the tests, as for a feature gate, we could use nonce length as one

**Comment by DaGenix** [comment]
Thanks!

**Pull request merged**
