### PR TITLE
Add support for SOSEMANUK cipher.

### PR DESCRIPTION
**Pull request by zenith-nz**
The SOSEMANUK cipher is added. SOSEMANUK, along with Salsa 20/8, Rabbit, and HC-128, is one of the ESTREAM finalist ciphers, and as such is worthy of inclusion. Test vectors are included - all tests pass. Speed on this MacBook Pro 2014 15" (2.3GHz i7) is ~ 275 MB/s. Performance can likely be improved... I made a SOSEMANUK implementation in C# that runs at 370 MB/s, for example.

### CODE REVIEW

**Comment by DaGenix** [comment]
@zenith-nz Again, I'm really sorry I haven't gotten back to you earlier on this. I will take a closer look tomorrow.

Do you know if SOSEMANUK is being used in any other libraries or algorithms?

Thanks!

**Comment by DaGenix** [comment]
The page hosting the test vectors that you reference seems to be down right now. I'm excited to merge this one that page comes back up or I can find somewhere else hosting the test vectors.

Thanks!

**Comment by zenith-nz** [comment]
Oh, the test vectors disappearing is frustrating! I'll see if I can track down their new home. It looks like they pulled access to the entire ESTREAM Subversion repository, as all the other cipher vectors are gone too it looks like.
As for if it's implemented in other libraries - yes, in crypto++/cryptopp.

**Comment by DaGenix** [comment]
I spent a little while trying to track them down as well, but without any success. Ideally all the algorithms in Rust-Crypto have test vectors hosted on external sites to make it easy for someone reviewing the code to confirm that its correct. If we can't find a good source for external vectors, that wouldn't prevent merging, though. Thanks!

**Comment by zenith-nz** [comment]
The link from ESTREAM http://www.ecrypt.eu.org/stream/p3ciphers/sosemanuk/sosemanuk_p3source.zip is still active, and contains two test vectors. I added them, along with a few others from ECRYPT.

**Comment by DaGenix** [comment]
Thanks!

**Pull request merged**
