### PR TITLE
Fix nightly errors

### PR DESCRIPTION
**Pull request by calvinmetcalf**
doesn't fix all the compiler warnings, but does pass

### CODE REVIEW

**Comment by DaGenix** [comment]
I think a few of the fixups here aren't quite right. I believe that `s.slice_to_mut(i)` becomes `s[..i]`. I'm not quite sure why none fo the tests were impacted, however.

**Comment by calvinmetcalf** [comment]
I think you are right

**Comment by calvinmetcalf** [comment]
updated

**Comment by DaGenix** [comment]
Thanks!

**Pull request merged**
