### PR TITLE
util: replace arch specific fixed_time_eq() with a generic version based on openssl and gnutls's equivalent functions

### LINKED ISSUE #302: util_helpers.c fails to build on ARM due to "{standard input}:39: Error: ARM register expected -- `ldrb r4,[$1] ldrb r5,[$2] " [...]
```
| Process didn't exit successfully: `/home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/git/target/release/build/rust-crypto-67f1ad94f3ffe5f4/build-script-build` (exit code: 101)
| --- stdout
| TARGET = Some("arm-poky-linux-gnueabi")
| TARGET = Some("arm-poky-linux-gnueabi")
| CARGO_MANIFEST_DIR = Some("/home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/rust-crypto-0.2.31")
| OUT_DIR = Some("/home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/git/target/arm-poky-linux-gnueabi/release/build/rust-crypto-67f1ad94f3ffe5f4/out")
| OPT_LEVEL = Some("3")
| PROFILE = Some("release")
| release 3
| TARGET = Some("arm-poky-linux-gnueabi")
| HOST = Some("x86_64-linux")
| CC_arm-poky-linux-gnueabi = None
| CC_arm_poky_linux_gnueabi = None
| TARGET_CC = Some("arm-poky-linux-gnueabi-gcc")
| TARGET = Some("arm-poky-linux-gnueabi")
| HOST = Some("x86_64-linux")
| CFLAGS_arm-poky-linux-gnueabi = None
| CFLAGS_arm_poky_linux_gnueabi = None
| TARGET_CFLAGS = Some(" -march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=/home/cody/obj/y/tmp/sysroots/beaglebone  -O2 -pipe -g -feliminate-unused-debug-types")
| TARGET = Some("arm-poky-linux-gnueabi")
| HOST = Some("x86_64-linux")
| CC_arm-poky-linux-gnueabi = None
| CC_arm_poky_linux_gnueabi = None
| TARGET_CC = Some("arm-poky-linux-gnueabi-gcc")
| running: "arm-poky-linux-gnueabi-gcc" "-O3" "-c" "-ffunction-sections" "-fdata-sections" "-march=armv7-a" "-mfloat-abi=hard" "-mfpu=neon" "-mtune=cortex-a8" "--sysroot=/home/cody/obj/y/tmp/sysroots/beaglebone" "-O2" "-pipe" "-g" "-feliminate-unused-debug-types" "-fPIC" "/home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/rust-crypto-0.2.31/src/util_helpers.c" "-o" "/home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/git/target/arm-poky-linux-gnueabi/release/build/rust-crypto-67f1ad94f3ffe5f4/out/src/util_helpers.o"
| 
| 
| command did not execute successfully, got: exit code: 1
| 
| 
| 
| --- stderr
| {standard input}: Assembler messages:
| {standard input}:39: Error: ARM register expected -- `ldrb r4,[$1] ldrb r5,[$2] eor r4,r4,r5 orr $0,$0,r4 add $1,$1,#1 add $2,$2,#1 subs $3,$3,#1 bne 1b'
| thread '<main>' panicked at 'explicit panic', /home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.6/src/lib.rs:459
| stack backtrace:
|    1:     0x7fe9986b8458 - sys::backtrace::write::hd8c95f651560dfe4y6r
|    2:     0x7fe9986c1244 - panicking::on_panic::h441ceaa2b70ecb64JMw
|    3:     0x7fe99867d6e2 - rt::unwind::begin_unwind_inner::h080f1ff0e70a38bcTrw
|    4:           0x409c20 - rt::unwind::begin_unwind::h17406813340456516896
|    5:           0x40a78c - run::haf0d0b3462d18e1fBva
|    6:           0x40725a - Config::compile::ha709ea40cfe7f8f3Wga
|    7:           0x4040b5 - compile_library::h5248a1a1b8319f602ca
|    8:           0x4034e5 - main::h6ac4eb617961c7e9faa
|                         at /home/cody/obj/y/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/coattail/0.0.0+gitAUTOINC+7882984c93-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/rust-crypto-0.2.31/build.rs:10
|    9:     0x7fe998745a78 - rust_try_inner
|   10:     0x7fe998745a65 - rust_try
|   11:     0x7fe9986c2d53 - rt::lang_start::h11cfe57bca456a8deHw
|   12:     0x7fe997e1278f - __libc_start_main
|   13:           0x4033a8 - _start
|   14:                0x0 - <unknown>
| 
```

### PR DESCRIPTION
**Pull request by jmesmon**
Should fix #302

### CODE REVIEW

**Comment by jmesmon** [comment]
We might want to consider just doing the same thing in plain rust code, assuming it works.

**Comment by myfreeweb** [comment]
[Of course it works in Rust](https://github.com/cesarb/constant_time_eq/blob/master/src/lib.rs).

**Comment by DaGenix** [comment]
Thanks for the PR and I'm sorry that I did not get to this in anything approaching a timely manner. The problem with doing this check in pure-rust code is there really is no way to guarantee that the compiler won't optimize it into a non-fixed time check. I believe that the original issue that resulted in this PR was fixed in #321. Thanks again and sorry for the massive delay.

**Comment by jmesmon** [comment]
> there really is no way to guarantee that the compiler won't optimize it into a non-fixed time check.

Then how is it good enough for gnutls and openssl and openbsd? 

openssl adds some use of volatile, which we could probably also adopt. gnutls uses almost exactly the code here. Openbsd uses more complex code to get ordering, but is also pure C with no volatiles.

**Comment by DaGenix** [comment]
To make sure we're talking about the same code, here are the implementations of secure memory clearing that I could find for GnuTLS, OpenBSD's LibreSSL-portable, and OpenSSL. If you've found other implementations, please post a link:

GnuTLS: https://gitlab.com/gnutls/gnutls/blob/master/lib/safe-memfuncs.c#L40
Seems to be be using volatile.

OpenBSD LibreSSL-portable: https://github.com/libressl-portable/openbsd/blob/master/src/lib/libc/string/explicit_bzero.c
Looks like its passing the cleared buffer into a function that the compiler can't analyze since its declared as weak. So, I believe this forces the compiler to actually clear it.

OpenSSL: https://github.com/openssl/openssl/blob/349807608f31b20af01a342d0072bb92e0b036e2/crypto/mem_clr.c
This code just looks like its trying to confuse the compiler. I guess this works with current compilers, but, I don't see why some new compiler optimization can't come along and optimize this away.

So, I think you're right - we can do this without ASM. I'm concerned about just doing the XOR trick - it may confuse current compilers enough to prevent them from optimizing the clearing away, but I don't see why a sufficiently smart compiler couldn't optimize it away.

GnuTLS uses volatile, but last I checked (a while ago - so this may have changed), stable Rust didn't provide us a way to get volatile semantics, so, I don't think we can use that mechanism. The OpenBSD approach looks interesting. I don't think we have any way to use a weakly versioned symbol in stable Rust, but, we could pass it to a function that the Rust compiler can't see - a do-nothing C function I _think_ would work (passing it to a no-op asm!() block might also work, but that only works on nightly). The OpenSSL approach seems risky, so, I don't see that as an appealing way to do this.

So, the OpenBSD approach but modified to use a C function seems like it might hold promise.

What do you think? Do you have other examples?

**Comment by jmesmon** [comment]
Ticket was originally about `fixed_time_eq` so I focused on memcmp/memeq impls:

- OpenSSL: https://github.com/openssl/openssl/blob/master/crypto/cryptlib.c#L470
 - volatile + xor
- OpenBSD: https://github.com/libressl-portable/openbsd/blob/master/src/lib/libc/string/timingsafe_memcmp.c
 - not volatile, not clearly xor, gets ordering (others just check equality).
- Gnutls: https://gitlab.com/gnutls/gnutls/blob/master/lib/safe-memfuncs.c#L70
 - plain xor

It looks like you're correct that stable rust doesn't yet have anything like volatile (I thought we had gotten volatile_store/volatile_load at some point, but I guess I was mistaken, they are still unstable).

For zeroing, a nop-c function sounds interesting except that relying only on it might allow LTO to optimize things. 

For equality, for plain xor to be an issue the optimizer would need to understand that the result of the loop is only used as a boolean, then infer that it can short circuit the updating of status once status is non-zero. It seems feasible, but I'm not sure if it's actually that smart.

Ideally, we'd have something like a stable black_box, which would prevent this. It appears that right now black_box is impled using `asm!`, so we can't have it in stable rust.

Using a callout to a C function might be the best thing right now.

**Comment by DaGenix** [comment]
Ah, I'm sorry. My reading comprehension is apparently quite bad.

So, we basically have two types of implementations, the OpenSSL one with volatile (which we can't do in stable Rust) and the LibreSSL / GnuTLS ones which rely on confusing the optimizer sufficiently. I find this all quite confusing - the OpenSSL developers seem to have felt that the risk of the optimizer turning it into a `memcmp` was sufficient to use `volatile`. The OpenSSL  / LibreSSL developers clearly don't feel that way. I don't really know who is right, which is why I went with a plain assembly version - I do feel confident that that won't be impacted by the optimizer.

I'm concerned trying to confuse the optimizer enough to let the code alone - I don't think that any current compiler can figure that out, but I don't follow compiler optimization development closely enough to really know if any new optimization coming down the pipe will. So, the OpenSSL solution is appealing to me if we call it as a C function. I do want to think over a bit of their comment some more: "The second problem cannot be resolved in any Standard-compliant way but this works the problem around. Compilers typically react to pointers to volatile by preserving the reads and writes through them. The latter is not required by the Standard if the memory pointed to is not volatile.". That's mildly concerning since it sounds like they think even with `volatile` the optimizer still might might be able to turn it into a `memcmp`. However, I _think_ we'd be safe from that since we'd be calling it using FFI which would prevent the Rust optimizer from seeing whats going on in that function and the C optimizer from seeing how the function is actually used. What do you think?

**Pull request closed without merging**
